const API_BASE_URL_DEVELOPMENT = 'http://localhost:5196';
const API_BASE_URL_PRODUCTION = 'http://appname.azurewebsites.net';

const ENDPOINTS = {
    GET_ALL_QUESTIONS: 'get-all-questions',
    GET_QUESTION_BY_ID: 'get-question-by-id',
    CREATE_QUESTION: 'create-question',
    UPDATE_QUESTION: 'update-question',
    DELETE_QUESTION_BY_ID: 'delete-question-by-id'
};

const development = {
    API_URL_GET_ALL_QUESTIONS: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.GET_ALL_QUESTIONS}`,
    API_URL_GET_QUESTION_BY_ID: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.GET_QUESTION_BY_ID}`,
    API_URL_CREATE_QUESTION: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.CREATE_QUESTION}`,
    API_URL_UPDATE_QUESTION: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.UPDATE_QUESTION}`,
    API_URL_DELETE_QUESTION_BY_ID: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.DELETE_QUESTION_BY_ID}`,
};

const production = {
    API_URL_GET_ALL_QUESTIONS: `${API_BASE_URL_PRODUCTION}/${ENDPOINTS.GET_ALL_QUESTIONS}`,
    API_URL_GET_QUESTION_BY_ID: `${API_BASE_URL_PRODUCTION}/${ENDPOINTS.GET_QUESTION_BY_ID}`,
    API_URL_CREATE_QUESTION: `${API_BASE_URL_PRODUCTION}/${ENDPOINTS.CREATE_QUESTION}`,
    API_URL_UPDATE_QUESTION: `${API_BASE_URL_PRODUCTION}/${ENDPOINTS.UPDATE_QUESTION}`,
    API_URL_DELETE_QUESTION_BY_ID: `${API_BASE_URL_PRODUCTION}/${ENDPOINTS.DELETE_QUESTION_BY_ID}`,
};

const Constants = process.env.NODE_ENV === 'development' ? development : production;

export default Constants;
