const API_BASE_URL_DEVELOPMENT = 'http://localhost:5196';

const ENDPOINTS = {
    GET_ALL_QUESTIONS: 'get-all-questions',
    GET_QUESTION_BY_ID: 'get-question-by-id',
    CREATE_QUESTION: 'create-question',
    UPDATE_QUESTION: 'update-question',
    DELETE_QUESTION_BY_ID: 'delete-question-by-id',

    GET_ALL_SURVEYS: 'get-all-surveys',
    GET_SURVEY_BY_ID: 'get-survey-by-id',
    CREATE_SURVEY: 'create-survey',
    UPDATE_SURVEY: 'update-survey',
    DELETE_SURVEY_BY_ID: 'delete-survey-by-id',

    GET_ALL_SURVEY_ANSWERS: 'get-all-survey-answers',
    GET_SURVEY_ANSWER_BY_ID: 'get-survey-answer-by-id',
    CREATE_SURVEY_ANSWER: 'create-survey-answer',
    UPDATE_SURVEY_ANSWER: 'update-survey-answer',
    DELETE_SURVEY_ANSWER_BY_ID: 'delete-survey-answer-by-id'
};

const development = {
    API_URL_GET_ALL_QUESTIONS: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.GET_ALL_QUESTIONS}`,
    API_URL_GET_QUESTION_BY_ID: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.GET_QUESTION_BY_ID}`,
    API_URL_CREATE_QUESTION: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.CREATE_QUESTION}`,
    API_URL_UPDATE_QUESTION: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.UPDATE_QUESTION}`,
    API_URL_DELETE_QUESTION_BY_ID: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.DELETE_QUESTION_BY_ID}`,

    API_URL_GET_ALL_SURVEYS: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.GET_ALL_SURVEYS}`,
    API_URL_GET_SURVEY_BY_ID: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.GET_SURVEY_BY_ID}`,
    API_URL_CREATE_SURVEY: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.CREATE_SURVEY}`,
    API_URL_UPDATE_SURVEY: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.UPDATE_SURVEY}`,
    API_URL_DELETE_SURVEY_BY_ID: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.DELETE_SURVEY_BY_ID}`,
    
    API_URL_GET_ALL_SURVEY_ANSWERS: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.GET_ALL_SURVEY_ANSWERS}`,
    API_URL_GET_SURVEY_ANSWER_BY_ID: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.GET_SURVEY_ANSWER_BY_ID}`,
    API_URL_CREATE_SURVEY_ANSWER: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.CREATE_SURVEY_ANSWER}`,
    API_URL_UPDATE_SURVEY_ANSWER: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.UPDATE_SURVEY_ANSWER}`,
    API_URL_DELETE_SURVEY_ANSWER_BY_ID: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.DELETE_SURVEY_ANSWER_BY_ID}`,
};

const Constants = development;

export default Constants;
